### ISSUE TITLE
Does glove.6B.50d.txt support Chinese?

### ISSUE THREAD

**Issue by tectal** [littleflow3r/Attention_based_BiLSTM_for_Relation_Classification#1]
Does glove.6B.50d.txt support Chinese?

**Comment by tectal** [comment]
？？？thanks

**Comment by susantiyuni** [comment]
Very sorry for my late reply. The glove.6B.50d.txt is vector pretrained from English text (https://nlp.stanford.edu/projects/glove/), so it does not support Chinese. Probably you can find pretrained vector for Chinese (https://github.com/Embedding/Chinese-Word-Vectors), though it is word2vec, not glove.
